version: "3.9"
services:
  web:
    container_name: web-python
    build: .
    ports: 
      - "${WEB_PORT:-8000}:5000"
    volumes: 
      - .:/code
    environment:
      FLASK_DEBUG: true
  redis:
    container_name: redis
    image: "redis:alpine"
    ports:
      - "6379:6379"
  mysql:
    container_name: mysql
    image: "mysql:8.0.31"
    ports:
      - "3306:3306"
      - "33060:33060"
    volumes:
      - /data/mysql:/var/lib/mysql
  nacos:
    container_name: nacos
    image: "nacos/nacos-server:v2.1.2"
    ports:
      - "8848:8848"
      - "9848:9848"
    environment:
      MODE: standalone
  mongo:
    container_name: mongo
    image: "mongo:6.0.3"
    ports:
      - "27017:27017"
  minio:
    container_name: minio
    image: "quay.io/minio/minio"
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - "/home/keepthinker/minio/data:/data" 
    environment:
      MINIO_ROOT_USER: "username"
      MINIO_ROOT_PASSWORD: "password"
    command:
      server /data  --console-address ":9090"
  sftp:
    container_name: sftp
    image: atmoz/sftp:alpine
    volumes:
        - /home/keepthinker/transfer:/home/sftp/transfer
        - /home/keepthinker/temp:/home/sftp/temp
    ports:
        - "2222:22"
    command: sftp:sftp:1001
